### ISSUE TITLE
`v.writable_copy().matrix().sum()` is different from `v.matrix().sum()`

### ISSUE THREAD

**Issue by RodenLuo** [nanovis/DiffFitViewer#18]
Hi @tomgoddard, 

With EMD-29900 open in ChimeraX, and running the following script shows that the sums of the matrix are different for the original map and the writable copy. Am I doing anything wrong? Thanks. 

```python
from chimerax.map.volume import volume_list
v = volume_list(session)[0]
v.matrix().sum()
Out[5]: -3153.0344

volume_copy = v.writable_copy()
volume_copy.matrix().sum()
Out[6]: -25224.293
```

And the surface looks different at the same threshold level. 

Original volume: 

![image](https://github.com/nanovis/DiffFitViewer/assets/8460424/5c76f6b6-1e06-4757-95d7-c4131e702a9c)

Writable copy: 

![image](https://github.com/nanovis/DiffFitViewer/assets/8460424/8d39abde-ec23-4ba4-97b8-e564c6758d2e)

**Comment by RodenLuo** [comment]
I just figured out it is because of the step. If I set the volume's step to 1, the sums and the visuals are then the same. 

```python
from chimerax.core.commands import run
from chimerax.map.volume import volume_list
v = volume_list(session)[0]
run(session, f"volume #{v.id[0]} step 1")

volume_copy = v.writable_copy()

v.matrix().sum()

volume_copy.matrix().sum()
```

**Comment by tomgoddard** [comment]
Right.  The Volume.matrix() returns the numpy 3D array for the currently displayed subsampled region.  If you want the full volume box and at full resolution use Volume.full_matrix().
