### ISSUE TITLE
ChimeraX camera right vector needed 

### ISSUE THREAD

**Issue by RodenLuo** [nanovis/DiffFitViewer#31]
Hi @tomgoddard, 

I'm in need of the right vector for the camera in the world space, but I could not figure out how to get it for quite some time. Could you please kindly jump in and help here at your convenience? I attach what I have tried at the end. 

I'm also in need of a "camera changed" trigger. The following line is in [Well Known Triggers](https://www.rbvi.ucsf.edu/chimerax/docs/devel/well_known_triggers.html). 

> Rotations and translations of models typically change the position of the camera relative to the models and not the positions of the models themselves.

I need exactly a trigger for this. I find `'graphics update'` seems to be the closest one and plan to use it. Kindly let me know if there is a better option. 

Many thanks! 

--- 
What I have tried for the right vector of the camera. 

```python
cam = session.main_view.camera
dir(cam)
Out[6]: 
[
...
 '_pixel_shift',
 '_position',
 'clear_special_render_modes',
 'combine_rendered_camera_views',
 'delete',
 'do_swap_buffers',
 'draw_background',
 'field_of_view',
 'get_position',
 'name',
 'number_of_views',
 'position',
 'projection_matrix',
 'ray',
 'rectangle_bounding_planes',
 'redraw_needed',
 'set_fixed_pixel_shift',
 'set_position',
 'set_render_target',
 'set_special_render_modes',
 'view',
 'view_all',
 'view_direction',
 'view_pixel_shift',
 'view_width']
```

Here, I indeed get the `view_direction`. If I can find the up vector, then a cross-product would do the job. But I could not find the up vector. 

I have found the following lines in `ChimeraX-1.7.1-Dev\bin\Lib\site-packages\chimerax\graphics\opengl.py` under the `Lighting` class. I cannot comprehend it very well. But I think these values are already in the camera space. 

> Directions are unit vectors in camera coordinates (x right, y up, z
    opposite camera view).
    ...
    :ivar key_light_direction: (.577, -.577, -.577)
    :ivar fill_light_direction: (-.2, -.2, -.959)

Also looked into the following in `ChimeraX-1.7.1-Dev\bin\Lib\site-packages\chimerax\graphics\view.py` 

```python
            if r.recording_opengl:
                from . import gllist
                cp = gllist.ViewMatrixFunc(self, vnum)
            else:
                cp = camera.get_position(vnum)
            self._view_matrix = vm = cp.inverse(is_orthonormal = True)
            r.set_view_matrix(vm)
```

and from `ChimeraX-1.7.1-Dev\bin\Lib\site-packages\chimerax\graphics\gllist.py`
```python
# Set view matrix used in setting model view shader variable.
class ViewMatrixFunc(MatrixFunc):
    def __init__(self, view, view_num):
        self._view = view
        self._view_num = view_num
        MatrixFunc.__init__(self, 'view matrix', self._view_matrix)
    def _view_matrix(self):
        return self._view.camera.get_position(self._view_num)
```

The camera position is a `Place` object. 

```python
session.main_view.camera.get_position()
Out[1]: <chimerax.geometry.place.Place at 0x1cb900f1510>

session.main_view.camera.get_position().matrix
Out[2]: 
array([[ 3.60291038e-01,  2.18214999e-02,  9.32584682e-01,
         8.08866564e+02],
       [ 3.42390964e-01,  9.26856556e-01, -1.53965424e-01,
         5.55485564e+01],
       [-8.67731984e-01,  3.74780931e-01,  3.26466626e-01,
         3.74822533e+02]])
```

Also read these functions from `ChimeraX-1.7.1-Dev\bin\Lib\site-packages\chimerax\graphics\view.py`, but got no insights. 

```python
    def move(self, tf, drawings=None):
        '''
        Move camera to simulate a motion of drawings.
        Transform is in scene coordinates.
        '''
        if drawings is None:
            c = self.camera
            c.position = tf.inverse() * c.position
        else:
            for d in drawings:
                d.scene_position = tf * d.scene_position

    def initial_camera_view(self, pad = 0.05, set_pivot = True):
        '''Set the camera position to show all displayed drawings,
        looking down the z axis.'''
        b = self.drawing_bounds()
        if b is None:
            return
        c = self.camera
        from chimerax.geometry import identity
        c.position = identity()
        c.view_all(b, window_size = self.window_size, pad = pad)
        if set_pivot:
            self._center_of_rotation = cr = b.center()
            self._update_center_of_rotation = True

    def win_coord(self, pt, camera=None, view_num=None):
        """Convert world coordinate to window coordinate"""
        # TODO: extend to handle numpy array of points
        c = self.camera if camera is None else camera
        near_far = self.near_far_distances(c, view_num)
        pm = c.projection_matrix(near_far, view_num, self.window_size)
        inv_position = c.position.inverse().opengl_matrix()
        from numpy import array, float32, concatenate
        xpt = concatenate((pt, [1])) @ inv_position @ pm
        width, height = self.window_size
        win_pt = array([
            (xpt[0] + 1) * width / 2,
            (xpt[1] + 1) * height / 2,
            (xpt[2] + 1) / 2
        ], dtype=float32)
        return win_pt
```

I also could not figure out how to trigger a breakpoint after a rotation...

**Comment by tomgoddard** [comment]
The ChimeraX Camera class has a position attribute that gives the origin and view direction of the camera in the scene coordinates as described in the programming manual

	https://www.cgl.ucsf.edu/chimerax/docs/devel/modules/graphics/graphics.html#chimerax.graphics.camera.Camera

The value is a Place instance.  If you look at the Place class documentation in the manual

	https://www.cgl.ucsf.edu/chimerax/docs/devel/modules/geometry/geometry.html#chimerax.geometry.place.Place

it shows it has an axes() method that will return the camera axes.  So

	x_axis = camera.position.axes()[0]

should give you what you need.

**Comment by RodenLuo** [comment]
Many thanks, Tom! I believe this is what I have been looking for. I will
give it a try once I get back to my dev environment.
